In [4]:
import numpy as np
import os, sys

notebook_dir = %pwd
project_root = os.path.abspath(os.path.join(notebook_dir, ".."))
if project_root not in sys.path:
    sys.path.append(project_root)

import src.rec_system.rec as recommendation


a=[.3,.5,.2]
b=[.2,.2,.8]
c=[.01,.01,.98]
d=[.6,.2,.2]
e=[.1,.8,.1]
f=[0,0,1]

songs=np.array([a,b,c,d,e,f])
similarity,reccomendations= recommendation.generate_similarities_recommendations(tot)
print('cosine similarity matrix')
print(similarity)
print('recommendation array',reccomendations)

cosine similarity matrix
[[-1.          0.61177529  0.33765025  0.78258558  0.89856345  0.32444284]
 [ 0.61177529 -1.          0.94752064  0.56853524  0.37716825  0.94280904]
 [ 0.33765025  0.94752064 -1.          0.31378526  0.13438182  0.99989589]
 [ 0.78258558  0.56853524  0.31378526 -1.          0.44536177  0.30151134]
 [ 0.89856345  0.37716825  0.13438182  0.44536177 -1.          0.12309149]
 [ 0.32444284  0.94280904  0.99989589  0.30151134  0.12309149 -1.        ]]
recommendation array [4 2 5 0 0 2]


In [2]:
filepath = "updated_track_probabilities"
sim, rec, loss = recommendation.load_csv_gen_recommendations(filepath)
print(rec)

[ 35  11 903  97  30 740  87  33   0  10  88   1  15  20  37  22  22  24
  20  26  13  22  21  25  17  23  19  26  27  90   4  89  34  95  85  38
  12  14  94  31  50  48  28  48  68  47  41  45  41 507  40  73  92  57
 689  76   6  53  80  54  55  79  80  84  40  66  63  84  45  68 909  83
  65  51  43  53  55  84 973  83  58  78  55  79  63  34  29  85  97  31
  92  99  52  20  38  30 507   3  79  91 115 119 163 120 186 127 134 124
 182 160 165 112 111 144 187 100 169 128 187 103 103 123 150 158 107 119
 141 111 117 163 173 140 140 116 181 162 155 164 172 196 131 126 190 153
 113 193 149 174 153 156 122 146 156 143 196 136 149 159 123 157 157 160
 157 150 137 110 164 144 164 116 141 176 163 147 175 174 171 128 122 138
 190 175 171 105 100 124 178 114 108 191 142 189 198 165 137 194 156 158
 136 525 241 214 236 205 254 233 242 241 254 239 866 866 240 704 201 947
 236 214 277 226 226 266 225 273 248 222 220 277 222 216 236 953 262 205
 243 210 216 238 233 209 212 212 206 245 866 243 22